package byNotes3;

public class Try_Catch_Block {
	public static void main(String[] args) {
		
		int a=12,b=0,c=0;
		if(b==0) {
		 throw new ArithmeticException("Not Valid The Number Pls Check Once Sachin....");
		}
//		try{
//			c = a/b;
//			System.out.println(" a/b = "+c);
//		}
//		catch(ArithmeticException e){
//			System.out.println("pls enter the valid number....");
//		}
//		finally {
//			System.out.println("Your Welcome...");
//		}
	}
}
